name: First Workflow

on:
  push:
    branches:
      - master  # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some task
        run: echo "First workflow completed successfully!"
