name: Source Workflow
on:
  workflow_dispatch:
      
run-name: ${{ github.actor }} is testing out GitHub Actions  🚀

jobs:
  trigger-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in another repo
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_GITHUB_TOKEN }}" \
          https://api.github.com/repos/browserstack/qa-common-scripts/actions/workflows/qd-single-job.yml/dispatches \
          -d '{"ref":"master"}'
